[package]
name = "aoc-2021-rust"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# regex = "1.5.4"
